### ISSUE TITLE
Forensics (Detectives possibly not included) Bug Report. Trouble with evidence lockup and police tapes.

### ISSUE THREAD

**Issue by Dude4Life** [WkSavage/N.T.C-Hollowstone#9]
1) Forensics don't have the ID access for getting inside the evidence lockup room. 

2) Forensics also cannot lift up deployed police tapes, which means they have to break the police tapeline in order to pass through those. (Tried this on all intents) But then they also have to redeploy the tape if it's taken down.

Not that big of a problem, just would help with the immersion if it could be fixed.

**Comment by WkSavage** [comment]
Both most likely have to do with an access issue. simple fix.

**Comment by WkSavage** [comment]
should be fixed
